
services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - split.wsgi:application
      - --bind
      - "127.0.0.1:8000"

    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - ./split/split/database:/split/database
      - static_volume:/var/www/static
      - media_volume:/var/www/media
