# Generated by Django 4.2.23 on 2025-07-15 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costdetail',
            name='people_cost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.people'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costdetail',
            name='people_share',
            field=models.ManyToManyField(related_name='people_share', to='main.people'),
        ),
        migrations.AddField(
            model_name='people',
            name='spent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.cost'),
            preserve_default=False,
        ),
    ]
