# Generated by Django 4.2.23 on 2025-07-15 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_costdetail_people_cost_costdetail_people_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costdetail',
            name='spent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.cost'),
            preserve_default=False,
        ),
    ]
