# Generated by Django 4.2.23 on 2025-07-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_costdetail_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costdetail',
            name='spent',
        ),
    ]
