# Generated by Django 4.2.23 on 2025-07-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_costdetail_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='costdetail',
            name='cost',
            field=models.ManyToManyField(to='main.cost'),
        ),
    ]
