# Generated by Django 4.2.23 on 2025-07-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_costdetail_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costdetail',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='people',
            name='spent',
        ),
    ]
