# Generated by Django 4.2.23 on 2025-07-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cost_cost_detail_cost_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='cost_detail',
            field=models.ManyToManyField(related_name='cost', to='main.costdetail'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='people',
            field=models.ManyToManyField(related_name='cost', to='main.people'),
        ),
    ]
