# Generated by Django 4.2.23 on 2025-07-16 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_cost_cost_detail_alter_cost_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='cost_detail',
        ),
    ]
