# Generated by Django 4.2.23 on 2025-07-16 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_cost_cost_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='costdetail',
            name='cost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='costdetail', to='main.cost'),
            preserve_default=False,
        ),
    ]
