# Generated by Django 4.2.23 on 2025-07-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_costdetail_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='people',
        ),
    ]
