# Generated by Django 4.2.23 on 2025-07-16 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_cost_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='cost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='peoples', to='main.cost'),
            preserve_default=False,
        ),
    ]
