# Generated by Django 4.2.23 on 2025-07-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_people_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='costdetail',
            name='name',
            field=models.CharField(default='food', max_length=150),
        ),
    ]
