# Generated by Django 4.2.23 on 2025-07-21 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_costdetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
